config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :tasks, only: [:index, :create, :update, :destroy]

  root ("tasks#index")
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true

  def self.incomplete
    where(completed: false)
  end

  def self.complete
    where(completed: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_login
  def index
    @incomplete_tasks = current_user.tasks.incomplete
    @complete_tasks = current_user.tasks.complete
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      render @task
    else
      render partial: "error_messages",
        locals: { target: @task },
        status: 422
    end
  end

  def update
    task = current_user.tasks.find(params[:id])
    task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    task.destroy
    render nothing: true
  end
  private

  def task_params
    params.require(:task).permit(:title, :description, :completed)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error_messages.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize target.errors.count, "error" %> prevented the form from saving </h2>
  <% target.errors.full_messages do |message| %>
    skjdhflksjdhf
    <li><%= message %> </li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if signed_in? %>
      <%= link_to "Sign out", session_path, method: :delete %>
  <% else %>
      <%= link_to "Sign in", new_session_path %>
      <%= link_to "Sign up", new_user_path %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/tasks/_task.html.erb
<li><strong><%= task.title %></strong> --- <%= task.description %></li>

<%= form_for task do |form| %>
  <%= form.hidden_field :completed, value: 1 %>

  <%= form.submit "Complete task" %>
<% end %>

<%= button_to "Delete Task", task_path(task), method: :delete %>

app/views/tasks/index.html.erb
<h1> Welcome </h1>
<div id="errors"></div>
<%= form_for @task do |form| %>
  <%= render "error_messages", target: @task %>
  <div>
    <%=form.label :title %>
    <%=form.text_field :title %>
  </div>

  <div>
    <%=form.label :description %>
    <%=form.text_field :description %>
  </div>

  <div>
  <%= form.submit %>
  </div>
<%end%>


<h3>Incomplete</h3>
<ul id="incomplete_task_list">
  <%= render @incomplete_tasks %>
</ul>
<h3>complete</h3>
<ul id="complete_task_list">
  <%= render @complete_tasks %>
</ul>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>